#!/bin/bash

san_cmd_run() {

  local what="$1"

  if [[ -z "$what" ]] ; then
    ./libexec/e2-help.sh run
    exit
  else
    ./libexec/e2-hook.sh run -1 "${@}"
    ./libexec/e2-run.sh "${@}"
    ./libexec/e2-hook.sh run  1 "${@}"
  fi

}

san_cmd_edit() {

  local what="$1"

  [[ -z "$EDITOR" ]] && echo "EDITOR unset" && exit

  if [[ -z "$what" ]] ; then
    ./libexec/e2-help.sh edit
    exit
  else
    ./libexec/e2-hook.sh edit -1 "${@}"
    ./libexec/e2-edit.sh "${@}"
    ./libexec/e2-hook.sh edit  1 "${@}"
  fi

}

san_cmd_gen() {

  local what="$1"

  if [[ -z "$what" ]] ; then
    ./libexec/e2-help.sh gen
    exit
  else
    ./libexec/e2-hook.sh gen -1 "${@}"
    ./libexec/e2-gen.sh "${@}"
    ./libexec/e2-hook.sh gen  1 "${@}"
  fi

}

cmd="$1"

if [[ -z "$cmd" ]] ; then
  ./libexec/e2-help.sh help
  exit

elif [[ "$cmd" == "run" || "$cmd" == "r" ]] ; then
  shift
  san_cmd_run "${@}"

elif [[ "$cmd" == "edit" || "$cmd" == "e" ]] ; then
  shift
  san_cmd_edit "${@}"

elif [[ "$cmd" == "gen" || "$cmd" == "g" ]] ; then
  shift
  san_cmd_gen "${@}"

else
  echo "Unknown command: $cmd"
fi
