#!/bin/bash

san_cmd_run() {

  local cmd="$1"
  local lab="$2"

  if [[ -z "$cmd" ]] ; then
    ./libexec/e2-help.sh run
    exit
  elif [[ -z "$lab" && "$cmd" != "ls" && "$cmd" != "ln" ]] ; then
    echo "usage: run start <lab>"
    exit
  else
    ./libexec/e2-hook.sh run -1 "$cmd" "$lab"
    ./libexec/e2-run.sh "$cmd" "$lab"
    ./libexec/e2-hook.sh run  1 "$cmd" "$lab"
  fi

}

san_cmd_edit() {

  local what="$1"

  [[ -z "$EDITOR" ]] && echo "EDITOR unset" && exit

  if [[ -z "$what" ]] ; then
    ./libexec/e2-help.sh edit
    exit
  else
    ./libexec/e2-hook.sh edit -1 "${@}"
    ./libexec/e2-edit.sh "${@}"
    ./libexec/e2-hook.sh edit  1 "${@}"
  fi

}

san_cmd_gen() {

  local what="$1"

  if [[ -z "$what" ]] ; then
    ./libexec/e2-help.sh gen
    exit
  else
    ./libexec/e2-hook.sh gen -1 "${@}"
    ./libexec/e2-gen.sh "${@}"
    ./libexec/e2-hook.sh gen  1 "${@}"
  fi

}

cmd="$1"

if [[ -z "$cmd" ]] ; then
  ./libexec/e2-help.sh help
  exit

elif [[ "$cmd" == "run" ]] ; then
  shift
  san_cmd_run "${@}"

elif [[ "$cmd" == "edit" ]] ; then
  shift
  san_cmd_edit "${@}"

elif [[ "$cmd" == "gen" ]] ; then
  shift
  san_cmd_gen "${@}"

else
  echo "Unknown command: $cmd"
fi
