
  switch-{{ NetworkDashed }}:
    name: switch-{{ NetworkDashed }}
    driver: bridge    {# Reserves IP x.x.x.1 as default gateway, we can't re-assign it #}
    # internal: true  {# Disables docker's port bind with host #}
    ipam:
      driver: default
      config:
        - subnet: {{ Network }}/{{ Mask }}
          gateway: {{ Gateway }} {# To use a container as gateway the container's IP can't be x.x.x.1 #}
