services

  einar2:
    build:
      context: "../build/einar2"
      dockerfile: Dockerfile
    image: einar2:latest
    container_name: einar2
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    hostname: einar2
    # Comment out when done testing
    entrypoint: /bin/echo "Einar2 image built successfully. Stopping container."
