include:
  - ../../compose/docker-compose-base.yml
  - ../../compose/docker-compose-machines.yml
  - docker-compose-net.yml

services:

  e2-server-10.0.1.51:
    image: e2-server:latest
    container_name: e2-server-10.0.1.51
    stdin_open: true
    tty: true
    hostname: server-10-0-1-51 # dots don't work here
    ports:
      - "8081:80"
    networks:
      net-10-0-1-0:
        ipv4_address: 10.0.1.51

  e2-server-10.0.1.52:
    image: e2-server:latest
    container_name: e2-server-10.0.1.52
    stdin_open: true
    tty: true
    hostname: server-10-0-1-52 # dots don't work here
    ports:
      - "8082:80"
    networks:
      net-10-0-1-0:
        ipv4_address: 10.0.1.52
