# /etc/systctl.d/einar2.conf

# Disable reverse path filter for all interfaces
net.ipv4.conf.all.rp_filter=0

# Disable reverse path filter for newly created interfaces
net.ipv4.conf.default.rp_filter=0

# Enable forwarding of packages on the system
net.ipv4.ip_forward=1
