# =======================
# Custom machine example
# =======================
#
# The only mandatory section is [Docker], you
# can disable other sections by just removing them.
#

[Docker]
image       = "default"
command     = "/usr/sbin/named -f"
hostname    = "{{ Type }}-{{ Name }}"

[Environments]
EnvArray[]  = "DEFAULT_GATEWAY={{ DefaultGateway }}"

[Capabilities]
CapArray[]  = "NET_ADMIN"

[Sysctls]
SysArray[]  = "net.ipv4.conf.all.rp_filter=0"
SysArray[]  = "net.ipv4.conf.default.rp_filter=0"

[Volumes]
VolArray[]  = "./e2-{{ Type }}-{{ Name }}-named.d:/etc/named.d"

[Ports]
PortArray[] = "8080:80"
PortArray[] = "8443:443"
PortArray[] = "8053:53"

