networks:
  net-10-0-1-0:
    name: net-10-0-1-0
    driver: bridge # reserves IP x.x.x.1 as default gateway, we can't re-assign the IP
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1 # to use a container as gateway the container's IP can't be x.x.x.1
